harvester/node-disk-manager

- .drone.yml
As title, we publish the docker image under repo `rancher/harvester-node-disk-manager` at this moment and remove arm support temporarily.
> Switch image repo to rancher/harvester-node-disk-manager

- main.go
- pkg/block/block_device.go
- pkg/controller/blockdevice/controller.go
- pkg/option/option.go
- pkg/udev/uevent.go
Add periodic rescanning for blockdevices
- A new CLI flag `--rescan-interval`. Default to 60 seconds (feel free to discuss the default in comments)
- A simple periodic blockdevice rescanning mechanism that reuses the
logic from good old `RegisterNodeBlockDevices` function
1. Create a k8s cluster with longhorn installed.
2. Run the binary. e.g.`go run main.go`. Don't forget to specify `--namespace` and `--node-name`.
- You can add `--rescan-interval` with a small value, say `10` seconds, to watch the changes more efficiently.
3. Watch the changes of all blockdevice CR. 
3. Plug a raw disk (without any partition) on the machine
- Expect to see some block device CR being created.
4. Manually create or delete GPT partitions
- Expect to see the block device CR being created and delete at each …
> Periodic rescanning for blockdevices

- main.go
- pkg/controller/blockdevice/controller.go
- pkg/udev/uevent.go
When attaching/detaching/provisioning device from one node, it deletes blockdevices on other nodes.
In order to let each NDM instance perform operations only on its own node, we did following changes:
- Filter blockdevice by label "kubernetes.io/hostname" on blockdevice to
avoid NDM from accidentally modifying other nodes' resources.
- Provide valid args to construct blockdevice.controller for udev
We need to provide all valid args to blockdevice.controller in order to
let it work correctly. Therefore we need to
- Expose all fields of `blockdevice.controller`
- Modify `udev.NewUdev` signature to accept longhorn Node controller
- NDM now only concern blockdevice on the same node.
- Remove leader election (copied from #7)
This PR also fixed the update loop as well (11e05ac)
> Perform operations only on the node NDM located

- pkg/controller/blockdevice/controller.go
- pkg/udev/uevent.go
When we adding a new partition, more than one uevents of that partition are generated, which in the sequence: add, remove, add. This behaviour makes it difficult to blindly delete the blockdevice CR when receiving an uevent with remove action. 
We propose not to remove any parition. We only flag partitions inactive when receiving uevent with remove action against them. The actual removal of a partition device only happens when we tried to remove the whole disk.
At this moment we need to manually test it.
1. Create a k8s cluster with longhorn installed.
2. Run the binary. e.g.`go run main.go`. Don't forget to specify `--namespace` and `--node-name`.
3. Watch the changes of all blockdevice CR. 
3. Plug a raw disk (without any partition) on the machine
- Expect to see two blockdevices if you …
> Introduce inactive state for partition devices

- pkg/block/block_device.go
- pkg/controller/blockdevice/controller.go
- pkg/udev/uevent.go
Related to https://github.com/harvester/harvester/issues/1285
After force formatting a raw disk (e.g. without any partition such as `/dev/sda`), set `spec.fileSystem.provisioned` to false as we do want to provision it single root partition instead of the raw disk itself.
> Do not provision raw disk after force formatting

- main.go
- scripts/build
The change also fixes the problem that version variables are not
passed during building.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
> Display version in log on application start

- pkg/controller/blockdevice/controller.go
Status should be mountpoint from sysfs not the original spec.
Signed-off-by: Weihang Lo <weihang.lo@suse.com>
> Filesystem status must reflect values from sysfs

- main.go
- pkg/block/block_device.go
- pkg/block/util.go
- pkg/controller/blockdevice/controller.go
- pkg/filter/filter.go
- pkg/filter/label_filter.go
- pkg/filter/path_filter.go
- pkg/filter/vendor_filter.go
- pkg/option/option.go
- pkg/udev/uevent.go
Related issue: https://github.com/harvester/harvester/issues/1282
- Separate filter to two filter interface: DiskFilter and PartFilter
- Add new label filter which excludes partition based on given pattern of filesystem label
- Add new cli arg `--label-filter` and new environment variable `NDM_LABEL_FILTER`. It accept a comma separated glob patterns describing in [`path/filepath#Match`](https://pkg.go.dev/path/filepath#Match)
> You can test the docker image at [`weihanglo/node-disk-manager:label-filter`](https://hub.docker.com/layers/169481236/weihanglo/node-disk-manager/label-filter/images/sha256-8a73fe7d2bf56f6b4fa383154f5eb90f097a8838c956080df89825f833d96f45)
1. Run node-disk-manager with `--label-filter` arg, e.g. `--label-filter "COS_*"` to exclude partition with ext label starting …
> Able to exclude partition based on ext filesystem label

- pkg/controller/blockdevice/controller.go
- pkg/filter/filter_test.go
- pkg/filter/path_filter.go
- pkg/filter/vendor_filter.go
- pkg/util/util.go
`ContainsIgnoredCase` is actually `MatchesIgnoredCase`, so we create
another `MatchesIgnoredCase` to do the real job.
This PR also includes a tiny fix for updating the right blockdevice.
> Exclude disks that contains longhorn in their busPath

- pkg/block/block.go
- pkg/block/block_device.go
- pkg/block/util.go
- pkg/filter/filter.go
- pkg/filter/filter_test.go
- pkg/filter/part_type_filter.go
- pkg/filter/path_filter.go
Related: harvester/harvester#1382, harvester/harvester#1241
Introduce a new `pathTypeFilter`.
Partition like BIOS boot in GPT scheme should not be provisioned.
So do the parent disk of that partition. Thus, if any partition matches
excluded parttype, both the partition and its parent disk get excluded.
> New `pathTypeFilter` to exclude BIOS boot partition

- pkg/controller/blockdevice/controller.go
Related: harvester/harvester#1599
Callback reenqueue: node-disk-manager migth be deployed earlier than Longhorn. Thus, if NDM cannot find longhorn node to provision, it should re-enqueue the callback after 15s.
Refer to harvester/harvester#1599. 
You can 
1. deploy the first node, and then 
2. change the `--auto-provision-filter` arg for demonset/harvester-node-disk-manager to whatever you want to provision. 
3. Last, create a new join-cluster with disks matching that auto-provision pattern.
> Fix reconcile enqueue

- pkg/block/block.go
- pkg/block/block_device.go
- pkg/controller/blockdevice/blockdevice.go
- pkg/controller/blockdevice/controller.go
Related: harvester/harvester#1829  harvester/harvester#1874
Previously, NDM use device path like `/dev/sda` to retrieve underlying
filesystem info, which is risky because the path is unstable and not
consistent between each boot. In this commit we use filesystem UUID
stored in `blockdevice.Status.DeviceStatus.Details.UUID` to get the
stable filesystem info from UUID.
1. Add an extra disk to a host.
2. provision and unprovision it back-and-forth. The filesystem detection shall work as expected.
> Retrieve filesytem info based on fs UUID

- main.go
- pkg/block/block_device.go
- pkg/controller/blockdevice/controller.go
- pkg/disk/disk.go
- pkg/option/option.go
- pkg/udev/uevent.go
- pkg/util/util.go
Related: https://github.com/harvester/harvester/issues/1839
Add support to provision raw blocks directly but maintain the ability to provision partitions.
- 58aacbae68295409b8b604ed1f0f0ea99b9efda6 **Remove auto-gpt-generate flag**: We do not provide this feature anymore. Devices are required to have WWN attached in order to uniquely identify by NDM.
- 3fb3e4bdd28789605d41de552c58273af23d4f3f **Remove the auto partition logic**: Raw block device can now be provisioned by NDM to Longhorn directly.
- e1444ae72990965921a17ba74b71ad9d46c918fc **Retrieve realtime filesystem info from OS**: NDM does not rely on CR status anymore to determine filesystem status. Instead, it queries the info from OS directly.
- 43ba0430076e7694bf444522c6b09b817f1c90e3 **Get real devpath from persistent device …
> Support raw block devices provision

- pkg/block/block.go
- pkg/block/block_device.go
- pkg/filter/device_path_filter.go
- pkg/filter/filter_test.go
- pkg/filter/label_filter.go
Related: harvester/harvester#1924
After #26, raw block devices are enabled to be provisioned. As a result, label filter cannot filter out raw block since previously it excluded partitions only. This PR reuse the same logic of label filter on disks as well.
- Collect filesytem `LABEL` when a disk has a filesytem on it.
- Apply the same logic of label filter on disks as well.
Copy from the reproducible steps:
1. Install Harvester with default data disk set to a disk different from the OS disk, e.g. /dev/sda
1. Go to "Hosts" page -> Select the node -> "Edit Config" -> "Disks" page -> Click "Add Disk"
1. The default data disk should not in the drop-down list.
Another way to test:
1. Install a Harvester cluster
2. Add a disk. Format it as ext4 filesystem. 
3. Run `e2label /dev/your/disk …
> Apply label filter on disks

- package/Dockerfile
After #26, node disk manager doesn't perform any partition. This is leftover and should be removed.
Signed-off-by: Weihang Lo <weihang.lo@suse.com>
> Remove unused `parted` system packages

- main.go
- pkg/block/blkid.go
- pkg/block/block_device.go
- pkg/block/util.go
- pkg/controller/blockdevice/controller.go
- pkg/controller/blockdevice/scanner.go
- pkg/disk/disk.go
- pkg/udev/uevent.go
Related issue: harvester/harvester#1718
The problem of the original issue is that during disk formatting in a `OnBlockDeviceChange` call, `ScanBlockDevicesOnNode` periodically updates info of all block device CRs. When the disk formatting is finished and then tries to update the CR, it might hit the resource conflict error because `ScanBlockDevicesOnNode` have just updated the resources. That's where the race condition occur.
The basic gist of this pull request is to ensure that **only `OnBlockDeviceChange` can update** existing blockdevices. `ScanBlockDevicesOnNode` and uevent action handler only handle **create** and **delete** block device CRs.
Other changes in this PR:
- Extract scanner to its own file (CodeFactor forces me to do that...)
- Remove unused `status.state`.
- Lower the …
> Enforce that only `OnBlockDeviceChange` can update CR

- pkg/block/util.go
- pkg/controller/blockdevice/controller.go
- pkg/disk/disk.go
Related: harvester/harvester#1874
Starting from #26, NDM resolves device links to actual block device files. However, it only takes WWN into consideration. Since the GUID of blockdevice CR depends on WWN, UUID, and PTUUID (in this fablback order), NDM also needs a fallback chain to resolve to actual block device files.
1. Prepare a harvester cluster (single node is sufficient)
2. Prepare two disks
- Both without WWN
- Format one of the disk
- Partition the other disk
3. Plug-in both disks and expect two blockdevice CR to show up without errors
4. Unplug both disks and wait for 30s, expect two blockdevice CR to be removed.
5. Plug-in both disk again.
- Expect both disks to show up without errors
- Expect both disks to get the same `Name`s as the last time they plugged in.
1. Prepare a …
> Support resolve real dev path from UUID and PTUUID

- manifests/crds/harvesterhci.io_blockdevices.yaml
- pkg/apis/harvesterhci.io/v1beta1/types.go
- pkg/controller/blockdevice/controller.go
Related: https://github.com/harvester/harvester/issues/2149
Just adding a resolved device path to `status.deviceStatus.devPath` for client to display.
> Add `status.deviceStatus.devPath`

- manifests/crds/harvesterhci.io_blockdevices.yaml
- pkg/apis/harvesterhci.io/v1beta1/types.go
- pkg/controller/blockdevice/blockdevice.go
- pkg/controller/blockdevice/controller.go
- pkg/controller/blockdevice/scanner.go
Related: harvester/harvester#1936
Don't expose `mountpoint` to user. This should be an implementation details.
Compatibility notice: If there is a previous non-empty mount point exists, node-disk-manager would continue using that value.
1. Prepare a harvester cluster (single node is sufficient)
1. Prepare an extra disk and add it to the host via Harvester Dashboard.
1. Expect the disk
- is mounted (check with CLI `lsblk`, `mount`, etc.), and 
- volumes can be scheduled onto it. (check its existence in longhorn dashboard)
1. Remove the disk from the host via Harvester Dashboard
1. Expect the disk 
- is unmounted (check with CLI `lsblk`, `mount`, etc.), and
- volumes cannot be scheduled onto it. (check its existence in longhorn dashboard)
1. Provision it again and see if the disk become …
> Don't expose `blockdevice.spec.fileSystem.mountPoint` to user

- pkg/controller/blockdevice/controller.go
- pkg/controller/blockdevice/scanner.go
When reboot, device path might change but controller cannot detect
it during the reconciliation. We explicitly check and update the value
when scanner startup.
related: https://github.com/harvester/harvester/issues/2149#issuecomment-1110488173
> Update devpath if changed

- main.go
- pkg/controller/blockdevice/controller.go
- pkg/option/option.go
Use bounded channel to control the concurrent count of block device
formatting. The default case will be hit only when the channel is
full or empty
related: https://github.com/harvester/harvester/issues/1831
1. Add a bunch of disks to a node.
2. Specify the flag `--max-concurrent-ops` to a number you want to test for node-disk-manager. You may also specify `--debug` for the sake of convenience to validate the behaviour.
3. Simultaneously set all `blockdevices` resource under namespace `longhorn-system` with `spec.fileSystem.forceFormatted = true` and `spec.fileSystem.provisioned = true`
4. Observe that only specified count of formatting operations can execute at a time. You can check the presence of log message `Hit maximum concurrent count. Requeue device %s` to verify.
For instance, you …
> Use channel as semaphore to control concurrent ops

- .drone.yml
We do not release binary after this PR.
Users can get it from the image.
> drone: remove binary release

- .drone.yml
- Dockerfile.dapper
enable drone ci for arm builds and update dapper to not check for processor types
**Problem:**
**Solution:**
https://github.com/harvester/harvester/issues/371
**Test plan:**
> enable ci for arm

- main.go
**Problem:**
NDM created with the `hostNetwork: true`. This parameter will expose the whole port on this pod to the host.
So, we need to prevent listening to unnecessary ports on NDM pods.
**Solution:**
we can disable profiler by default. NDM does not use it generally.
https://github.com/harvester/harvester/issues/4212
**Test plan:**
make sure the host does not listen :6060
```
harvester-node-0:~ # ss -tnal |grep 6060
LISTEN 0      4096               *:6060             *:*
```
> process: do not enable profiler by default

- ci/scripts/upgrade_ndm.sh
- pkg/controller/blockdevice/scanner.go
- pkg/utils/virt.go
- tests/integration/test_1_disk_hotplug_test.go
**Problem:**
Get multiple blockdevice with the same WWN
**Solution:**
To prevent data broken with mis-operation, we should prevent creating the blockdevice with the same WWN.
https://github.com/harvester/harvester/issues/4494
**Test plan:**
1. Create scsi controller files
- controller.xml
```
<controller type='scsi' model='virtio-scsi' index='0'/>
```
Then, use following command to add virtio-scsi controller
```
virsh attach-device --domain <VM name> --file <controller file name> --live
```
2. Prepare two disk XML files with the same wwn as below:
- node-0-sda.xml
```
<disk type='file' device='disk'>
<driver name='qemu' type='qcow2'/>
<source file='/tmp/node-0-sda.qcow2'/>
<target dev='sda' bus='scsi'/>
<wwn>0x5000c50017654321</wwn>
</disk>
```
- node-0-sdb.xml
``` …
```
> scanner: should not add the same wwn device again

- .drone.yml
add drone pipeline for publishing multi-arch manifests
**Problem:**
**Solution:**
https://github.com/harvester/harvester/issues/371
**Test plan:**
> manifest publishing

- .drone.yml
Fix https://drone-publish.rancher.io/harvester/node-disk-manager/108/3/2
> drone: use environment instead env

- ci/charts/ndm-override.yaml
- main.go
- pkg/option/option.go
- pkg/udev/uevent.go
**Problem:**
The udev monitor will not work with any errors.
**Solution:**
We monitor the error and try to respawn it.
https://github.com/harvester/harvester/issues/4925
**Test plan:**
Because the original error is hard to reproduce, I added another inject error here.
1. set the parameter `inject-udev-monitor-error` as true.
2. try to add a disk and provision it should work
> uevent: should respawn the uevent monitor

- pkg/udev/uevent.go
**Problem:**
Prevent the channel will be used after error injection
**Solution:**
close channel when we level
**Test plan:**
> uevent: should close uevent channel

- ci/scripts/upgrade_ndm.sh
- go.mod
- pkg/block/block_device.go
- pkg/utils/command.go
- pkg/utils/process.go
- pkg/utils/utils.go
**Problem:**
Move ns related functions locally instead of extra packages
**Solution:**
Implement our own ns related ns functions
**Test plan:**
Make sure everything will be fine after that.
> Add ns related funcs

- .golangci.yaml
- Dockerfile.dapper
- go.mod
- main.go
- pkg/controller/blockdevice/controller.go
https://github.com/harvester/harvester/issues/5310
> Bump golangci-lint

- pkg/controller/blockdevice/scanner.go
**Problem:**
We encounter some weird issue that the ID is changed after reboot.
**Solution:**
Add these logs would help us to verify easily.
**Test plan:**
None
> scanner: add more logs

- pkg/controller/blockdevice/controller.go
- pkg/utils/command.go
- pkg/utils/utils.go
- tests/integration/test_1_disk_hotplug_test.go
**Problem:**
When the disk is gone, we cannot remove it on Harvester UI.
That's a regression after we introduce the inactive/corrupted concept.
**Solution:**
Improve the removing disk mechanism.
https://github.com/harvester/harvester/issues/5726
**Test plan:**
1. Create 3 node Harvester cluster
2. add an extra disk and provision it as Longhorn disk
3. remove the above disk (physically). (If you use kvm, try virtctl command with attach-device/detach-device)
4. Remove this provision disk on the Harvester UI
5. make sure both Harvester/Longhorn UI removed the above disk
**Nice to Have:**
> controller: improve the mechanism of disk removing

- deploy/charts/harvester-node-disk-manager/templates/daemonset.yaml
- deploy/charts/harvester-node-disk-manager/values.yaml
- main.go
- pkg/option/option.go
**Problem:**
Commit 7d5395f21c1167d2ad4bbe571d0e720e2ea61556 removed scanner polling, but the CLI option, environment variable and chart value remained.
**Solution:**
This PR
N/A
**Test plan:**
N/A
> Remove rescan-interval CLI option and env var

- .github/workflows/basic-ci.yaml
**Problem:**
We destroy VMs no matter whether we deploy VMs or not.
Sometimes, that might break a running test.
Also, I merge two jobs (image build/integration test) together. That can ensure we use the image ASAP
**Solution:**
Only destroy VM if we pass deployment stage
None
**Test plan:**
No need
> ci: improve the timing of tear down

- pkg/block/util.go
- pkg/udev/device.go
- pkg/udev/uevent.go
**Problem:**
When a device is removed, we're unable to determine the BD name (i.e. the name of the blockdevice CR) for logging purposes, because we're trying to figure it out based on device information in `/sys/class/block/...` and `/var/run/udev/data/...` but that isn't present anymore, because the device is gone.
**Solution:**
Use the data in the udev event instead for remove events. This change (IMO) simplifies `ActionHandler` a bit. I've also taken the liberty of introducing structured logging in that function, and I've included an (unrelated) small fix to an error string in `util.lsblk()`.
Log messages before this PR, when attaching/detaching a device (note the error messages and missing BD name on detach):
```
time="2024-07-16T12:21:36Z" level=info msg="Wake up scanner with add …
```
> udev: refactor ActionHandler to get BD name on remove

- .github/workflows/basic-ci.yaml
- go.mod
- package/Dockerfile
- pkg/controller/blockdevice/controller.go
- tests/integration/test_1_disk_hotplug_test.go
**Problem:**
bump golang 1.22.7 and bci-image 15.6
**Solution:**
bump golang 1.22.7 and bci-image 15.6
https://github.com/harvester/harvester/issues/6568
**Test plan:**
> common: bump golang 1.22.7 and bci image 15.6

- pkg/controller/blockdevice/scanner.go
- We should also consider the wwn of the added blockdevice in
the same round.
**Problem:**
It would not work well if two duplicate WWN devices wanted to join simultaneously.
**Solution:**
Should consider the WWNs even if in the same round
https://github.com/harvester/harvester/issues/6604
**Test plan:**
> controller/scanner: should consider the wwn of the added blockdevice

- pkg/controller/blockdevice/controller.go
- pkg/provisioner/common.go
- pkg/utils/utils.go
**Problem:**
If multipathd is running and has taken over a device, `ResolvePersistentDevPath()` will end up returning a `/dev/dm-*` device path, which we don't want.  We want the real underyling device (e.g. `/dev/sda`).  If we take a `/dev/dm-*` path and later update the blockdevice CR with it, we lose all the interesting DeviceStatus information, like the WWN.
Happily, in this case, we can figure out the right path to use by checking `/dev/disk/by-path/` + the device's bus path. This has the added advantage of also working for block devices that have no WWN.
**Solution:**
This PR.
Note: we're not trying to make NDM support multipath devices here, we're just trying to avoid having it corrupt the blockdevice CRs if multipath happens to be active. …
> Use BusPath to resolve dm device paths

- pkg/controller/blockdevice/controller.go
- pkg/controller/blockdevice/scanner.go
- pkg/provisioner/longhornv1.go
**Problem:**
Missing mountpoint when provisioning the longhorn V1
**Solution:**
We need to improve the handling with the new provision field `Spec.Provision`.
Walk through the whole `Spec.Filesystem.Provisioned` logic and improve them.
None
**Test plan:**
Make sure the longhornV1 can works as usual only with the new provision field `Spec.Provision`.
> controller: consider the new provision field

- pkg/controller/blockdevice/scanner.go
- pkg/filter/vendor_filter.go
- pkg/provisioner/longhornv2.go
**Problem:**
1. Disks added for use by LHv2 are added successfully, but their status remains stuck with an error "spec and status of disks on node $NAME are being syncing and please retry later."
2. Active LHv2 volumes attached to VMs appear as `/dev/dm-*` and `/dev/nvme*` devices on the host. NDM sees these and thinks they're real disks, and then creates new BD CRs from those devices.
**Solution:**
1. Add a call to `reflect.DeepEqual()` to avoid unnecessary updates and resultant weird state.
2. Abuse the existing vendor filter to pick up SPDK devices, and explicitly exclude `/dev/dm-` devices in `ApplyExcludeFiltersForDisk()`.
Note: I intend to handle this more cleanly later as part of https://github.com/harvester/harvester/issues/5059 …
> Fix two issues encountered when testing LHv2 provisioning

- .github/workflows/basic-ci.yaml
**Problem:**
The CI teardown flow is not working.
Need always() to trigger the steps, or steps after the failure cannot be executed.
**Solution:**
Make sure the if-condition works
**Test plan:**
> ci: make sure the if-condition works

- pkg/controller/blockdevice/controller.go
- pkg/controller/blockdevice/scanner.go
- we should not set both `Spec.Filesystem.Provisioned` and
`Spec.Provision` or the remove operation would be blocked if
we only change one of these to false.
This is a side-effect that comes from 1877a4ef1743e4bb01b81179aacfe5b32da059ed.
For now, we will remove one of these two fields to ensure the delete operation
work. We still need mutator to help convert these two fields.
**Problem:**
The removal operation would be blocked if we only changed one of these to false.
**Solution:**
For now, we will remove one of these two fields to ensure the delete operation work.
**Test plan:**
> scanner: correct the autoProvision mechanism

- pkg/provisioner/longhornv2.go
**Problem:**
We need to force DiskDriver to "auto" if it's not explicitly set, because Longhorn also does that internally.  If we don't do this, the subsequent `reflect.DeepEqual()` in `LonghornV2Provisioner.Update()` will always fail because we have an empty string, but the LHN CR will have it set to "auto" which results in a weird resync loop.
**Solution:**
This PR.
https://github.com/harvester/harvester/issues/6709
**Test plan:**
Add an LHv2 disk. Verify we don't see the errors mentioned in the related issue.
> fix: set LHv2 DiskDriver to "auto" if unset

- pkg/provisioner/longhornv2.go
**Problem:**
When using the Longhorn V2 data engine, for NVMe devices where Longhorn decides to use the nvme bdev driver, device activation will fail if there's an existing filesystem. This does not appear to be a problem when using the aio driver.
**Solution:**
Run `wipefs -a $devPath` during provisioning.
Without this, we'll potentially have devices stuck unschedulable with an obscure error message like this:
`Disk c1fd02d173a3f4b9176705e9b2e37d39(0003:03:00.0) on node altra is not ready: failed to generate disk config: error: rpc error: code = Internal desc = rpc error: code = Internal desc = failed to add disk block device: failed to create disk bdev: failed to attach NVMe disk 0003:03:00.0: error sending message, id 3126, method bdev_nvme_attach_controller, params …
> fix: Call `wipefs -a` in LonghornV2Provisioner.Format()

- pkg/provisioner/lvm.go
- The filesystem metadata would break the pvcreate
**Problem:**
The filesystem metadata would break the pvcreate
**Solution:**
make sure the device is clean
**Test plan:**
> provisioner: ensure the device is ready before adding into volume group

- renovate.json
The [default configuration ](https://github.com/harvester/renovate/blob/bf6a43711f19c73e2c96e94132eeac8b630af1c8/renovate-default.json#L6C5-L10)doesn't work for this repo.
> ci: tune Renovate base branches [skip ci]

- pkg/controller/blockdevice/scanner.go
- when the node reboot, it might cause the device path change because of the interrupt order with the device. We need to update the device path once it changed.
**Problem:**
Sometimes we will see the duplicated status.deviceStatus.devPath of the blockdevice CR in the same node.
The device path would be change in following two cases:
1. device is temporarily gone and back.
2. Node reboot might also cause the device path change (depends on device interrupt).
So, we need to update the device path once it has changed
**Solution:**
Update device path once it has changed
https://github.com/harvester/harvester/issues/8164
**Test plan:**
Try to reboot, and you might see the spec.devPath is different from status.deviceStatus.devPath.
**NOTE**: It is hard to reproduce so that we …
> controller/blockdevice: should update DevPath once it changed

- go.mod
- vendor/modules.txt
Get rid of
```
go: github.com/openshift/api@v0.0.0: invalid version: unknown revision v0.0.0
go: github.com/openshift/client-go@v0.0.0: invalid version: unknown revision v0.0.0
go: github.com/rancher/rancher/pkg/apis@v0.0.0: invalid version: unknown revision pkg/apis/v0.0.0
```
The module versions were taken from the Harvester v1.5.1 which adds them as indirect requirements to node-disk-manager.
```
$ go mod graph | grep github.com/openshift/api
github.com/harvester/harvester@v1.5.1 github.com/openshift/api@v0.0.0
$ go mod graph | grep github.com/openshift/client-go     
github.com/harvester/harvester@v1.5.1 github.com/openshift/client-go@v0.0.0
$ go mod graph | grep github.com/rancher/rancher/pkg/apis
github.com/harvester/harvester@v1.5.1 github.com/rancher/rancher/pkg/apis@v0.0.0
```
> Fix go-mod warnings
