harvester/node-disk-manager

pkg/disk/mount_linux.go

To mount a new device on an existing directory of a read-only filesystem, NDM should not require the file system to be read-write.
We inspect the existence of the directory first to decide whether NDM need to execute `mkdir -p` or not.

Call mkdir only when diretory does not exist

---

pkg/controller/blockdevice/controller.go

A new block device status is derived from sysfs, and that results
in lacking `FileSystem.LastFormattedAt`. We copy that field before
`DeepEqual` comparison to reduce unnecessary updates.

Let SaveBlockDevice update more precisely

---

manifests/crds/harvesterhci.io_blockdevices.yaml
pkg/apis/harvesterhci.io/v1beta1/types.go

Related to harvester/harvester#1281

Print `spec.devPath` in kubectl by default

---

pkg/controller/blockdevice/controller.go
pkg/util/util.go

See https://github.com/harvester/harvester/issues/1414

Fix for invalid partition device paths with NVMe disks

---

pkg/filter/drive_type_filter.go
pkg/filter/filter.go
pkg/filter/filter_test.go

Supposed this won't change over time, so I hard-coded this filter. 
Related: https://github.com/harvester/harvester/issues/1623#issuecomment-985108607

Exclude disk whose driver type is neither HDD nor SSD

---

main.go
pkg/controller/blockdevice/controller.go

- `DefaulText` is real text. That shows on `--help`. `Value` does really for the default value.
Actually, if the `DefaultText` is nil, that would get the `Value` for it.
Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

controller: make parameter really work with cli module

---

main.go
pkg/controller/blockdevice/controller.go
pkg/controller/blockdevice/scanner.go

related issue: https://github.com/harvester/harvester/issues/2832

fix the disk tag missing when NDM respawn

---

pkg/generated/controllers/harvesterhci.io/v1beta1/blockdevice.go

fix drone ci and add this to the normal CI flow

ci related work

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/disk/mount_linux.go

**Description:**
fix lint error of https://drone-publish.rancher.io/harvester/node-disk-manager/71/1/2
**Test:**
Verified local build works.
```
Successfully built 5ec5762d82ba
Successfully tagged harvester/node-disk-manager:50e0fb2-amd64
Built harvester/node-disk-manager:50e0fb2-amd64
```

Fix lint error

---

.github/workflows/basic-ci.yaml

We could do that on the action runner. That does not take much time.

ci: add validations on action runners

---

.drone.yml

Update the build flow of drone

drone: update fetch operation before build

---

.drone.yml

fix https://drone-publish.rancher.io/harvester/node-disk-manager/111/3/2

drone: use fixed image name

---

ci/scripts/upgrade_ndm.sh

ci: fix typo

---

ci/scripts/upgrade_ndm.sh

**Problem:**
fix upgrade issue on CI
**Solution:**
We need more time to wait for the pod to respawn.
None
**Test plan:**
None

ci: make sure the upgrade could be tested

---

.github/workflows/basic-ci.yaml

**Problem:**
unified the runs-on
**Solution:**
unified the runs-on
**Test plan:**
None

ci: unified the runs-on

---

README.md
pkg/filter/path_filter.go
pkg/version/version.go

**Problem:**
I want to add some more details to the README file, a comment about how the version gets set during build, and fix a tiny bit of debug logging.
**Solution:**
This PR
N/A
**Test plan:**
N/A

A few minor tweaks

---

pkg/controller/blockdevice/scanner.go
pkg/udev/uevent.go
pkg/utils/virt.go
tests/integration/test_1_disk_hotplug_test.go

**Problem:**
We have problems with duplicated WWN as https://github.com/harvester/harvester/issues/5446#issuecomment-2112177685
**Solution:**
Should skip the handling with the udev ADD event
https://github.com/harvester/harvester/issues/4494
**Test plan:**
Please check the above issue.

fix the duplicated wwn case

---

go.mod
go.sum
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/config.go
vendor/golang.org/x/net/http2/config_go124.go
vendor/golang.org/x/net/http2/config_pre_go124.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/unencrypted.go
vendor/golang.org/x/net/http2/write.go
vendor/modules.txt

**Problem:**
CVE-2024-45338
**Solution:**
Bump `golang.org/x/net` v0.33.0
**Test plan:**

common: bump golang.org/x/net v0.33.0

---

.github/workflows/basic-ci.yaml
ci/charts/ndm-override.yaml
ci/scripts/deploy_ndm_chart.sh
ci/scripts/deploy_ndm_current.sh
ci/scripts/helpers.sh
ci/scripts/patch_ndm.sh
ci/scripts/upgrade_ndm.sh
pkg/controller/blockdevice/controller.go
tests/integration/test_0_single_disk_test.go
tests/integration/test_1_disk_hotplug_test.go
tests/integration/test_2_lvm_test.go

**Problem:**
The auto provision feature did not work in some cases.
**Solution:**
Fix the lacking of auto provision handling.
https://github.com/harvester/harvester/issues/7668
**Test plan:**
See comment: https://github.com/harvester/harvester/issues/7668#issuecomment-2673204104

fix auto provision feature not working in some cases

---

.github/workflows/nightly.yaml

**Problem:**
We need daily build for images
**Solution:**
add related GHA
**Test plan:**

GHA: add daily build for version-head image

---

.github/workflows/factory.yaml
.github/workflows/nightly.yaml

- we need to handle the different branch ourselves
**Problem:**
the scheduled action did not support branches
**Solution:**
we need to handle the different branch ourselves
**Test plan:**

GHA: fix the scheduled action did not support branches

---

pkg/controller/blockdevice/scanner.go

**Problem:**
In cases where disks are manually formatted to work around having no WWN, they get caught by the duplicate WWN checker.  This prevents adding multiple disks of this kind.
**Solution:**
In this case, disks are identified by FS UUID, which means we can safely skip the duplicate check anyway.
https://github.com/harvester/harvester/issues/7173
**Test plan:**
- Deploy a virtualized harvester cluster. One node is fine.
- Add two extra virtio disks (/dev/vdb, /dev/vdc) - these will not have WWNs.
- Initially, these two disks should not be visible in the Harvester UI if you try to add extra disks to a node.
- Run `mkfs /dev/vdb ; mkfs /dev/vdc` to make filesystems on those disks, then `kubectl -n harvester-system rollout restart …

fix: skip duplicate disk check if device has no WWN

---

.golangci.yaml
Dockerfile.dapper
pkg/controller/volumegroup/controller.go
pkg/provisioner/longhornv1.go
pkg/utils/command.go
tests/integration/test_0_single_disk_test.go
tests/integration/test_1_disk_hotplug_test.go

**Problem:**
**Solution:**
https://github.com/harvester/harvester/issues/8749
**Test plan:**

feat: upgrade golangci-lint to latest

---

renovate.json

**Problem:**
**Solution:**
**Test plan:**

fix(renovate): use base branches in default renovate
